name: animation_tools_dart
description: Various data classes for working with animations
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  vector_math:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
