name: animation_tools_dart
description: Various small helper classes for working with animation data.
version: 0.1.2
repository: https://github.com/nmfisher/animation_tools_dart

environment:
  sdk: ^3.0.0

dependencies:
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
